"""Load cleaned GradCafe applicant records into PostgreSQL.

Connection settings prefer DB_* variables, with legacy PG* fallbacks;
DATABASE_URL overrides those settings. Missing passwords are prompted for
without echo only in an interactive terminal. Provisioning requires an
administrator role, separate from the restricted Flask application role.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable, Sequence
from datetime import date, datetime
import getpass
import json
import math
import os
from pathlib import Path
import sys
from typing import Any

import psycopg
from psycopg import sql


DEFAULT_INPUT = Path(__file__).resolve().parent.parent / (
    "llm_extend_applicant_data.json"
)
DATE_FORMATS = ("%b %d, %Y", "%Y-%m-%d")
COLUMNS = (
    "program",
    "comments",
    "date_added",
    "url",
    "status",
    "term",
    "us_or_international",
    "gpa",
    "gre",
    "gre_v",
    "gre_aw",
    "degree",
    "llm_generated_program",
    "llm_generated_university",
)
EXPECTED_SCHEMA = {
    "p_id": "integer",
    "program": "text",
    "comments": "text",
    "date_added": "date",
    "url": "text",
    "status": "text",
    "term": "text",
    "us_or_international": "text",
    "gpa": "double precision",
    "gre": "double precision",
    "gre_v": "double precision",
    "gre_aw": "double precision",
    "degree": "text",
    "llm_generated_program": "text",
    "llm_generated_university": "text",
}

CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS applicants (
    p_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program text,
    comments text,
    date_added date,
    url text NOT NULL UNIQUE,
    status text,
    term text,
    us_or_international text,
    gpa double precision,
    gre double precision,
    gre_v double precision,
    gre_aw double precision,
    degree text,
    llm_generated_program text,
    llm_generated_university text
)
"""

INSERT_SQL = """
INSERT INTO applicants (
    program,
    comments,
    date_added,
    url,
    status,
    term,
    us_or_international,
    gpa,
    gre,
    gre_v,
    gre_aw,
    degree,
    llm_generated_program,
    llm_generated_university
) VALUES (
    %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s
)
ON CONFLICT (url) DO NOTHING
"""


def optional_text(value: object) -> str | None:
    """Return normalized text, using None for missing or blank values.

    Args:
        value: Source field to stringify and strip, or None.

    Returns:
        Trimmed text, or None when the input is missing or blank.
    """
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def optional_float(value: object, field: str) -> float | None:
    """Convert a supplied numeric value while preserving missing values.

    Args:
        value: Numeric source value, blank string, or None.
        field: Field name included in validation errors.

    Returns:
        A finite float, or None for a missing or blank input.

    Raises:
        ValueError: The value is nonnumeric, infinite, or NaN.
    """
    if value is None or (isinstance(value, str) and not value.strip()):
        return None
    try:
        number = float(value)
    except (TypeError, ValueError) as error:
        raise ValueError(f"{field} must be numeric, got {value!r}") from error
    if not math.isfinite(number):
        raise ValueError(f"{field} must be finite, got {value!r}")
    return number


def optional_date(value: object) -> date | None:
    """Convert source dates such as 'Feb 12, 2026' to date objects.

    Args:
        value: date, datetime, supported date string, blank string, or None.

    Returns:
        A date without time information, or None for missing input.

    Raises:
        ValueError: A nonblank string matches none of DATE_FORMATS.
    """
    if value is None or (isinstance(value, str) and not value.strip()):
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    text = str(value).strip()
    for date_format in DATE_FORMATS:
        try:
            return datetime.strptime(text, date_format).date()
        except ValueError:
            continue
    raise ValueError(f"date_added has an unsupported format: {value!r}")


def first_present(record: dict[str, Any], *keys: str) -> object:
    """Return the first nonblank value among equivalent source fields.

    Args:
        record: Source applicant dictionary, which is not modified.
        *keys: Equivalent field names in descending order of preference.

    Returns:
        The first non-None, nonblank value, or None. Zero remains valid.
    """
    for key in keys:
        value = record.get(key)
        if value is not None and not (
            isinstance(value, str) and not value.strip()
        ):
            return value
    return None


def normalize_record(record: dict[str, Any]) -> tuple[object, ...]:
    """Map one Module 2 object to the required applicants schema.

    Args:
        record: Applicant dictionary; legacy field aliases are accepted.

    Returns:
        Values ordered exactly as COLUMNS for parameterized insertion.
        Missing optional fields become None, which psycopg binds as NULL.

    Raises:
        ValueError: The URL is absent or a date/numeric value is invalid.
    """
    url = optional_text(record.get("url"))
    if url is None:
        raise ValueError("url is required to identify and deduplicate a row")

    values = {
        "program": optional_text(record.get("program")),
        "comments": optional_text(record.get("comments")),
        "date_added": optional_date(record.get("date_added")),
        "url": url,
        "status": optional_text(record.get("status")),
        "term": optional_text(record.get("term")),
        "us_or_international": optional_text(
            first_present(record, "us_or_international", "citizenship")
        ),
        "gpa": optional_float(record.get("gpa"), "gpa"),
        "gre": optional_float(
            first_present(record, "gre", "gre_quantitative"), "gre"
        ),
        "gre_v": optional_float(record.get("gre_v"), "gre_v"),
        "gre_aw": optional_float(record.get("gre_aw"), "gre_aw"),
        "degree": optional_text(record.get("degree")),
        "llm_generated_program": optional_text(
            first_present(
                record,
                "llm_generated_program",
                "llm-generated-program",
            )
        ),
        "llm_generated_university": optional_text(
            first_present(
                record,
                "llm_generated_university",
                "llm-generated-university",
            )
        ),
    }
    return tuple(values[column] for column in COLUMNS)


def read_records(filename: Path) -> list[dict[str, Any]]:
    """Read and validate the top-level JSON document.

    Args:
        filename: UTF-8 JSON input path, optionally with a byte-order mark.

    Returns:
        Applicant dictionaries in their original document order.

    Raises:
        ValueError: JSON is invalid or is not an array of objects.
        OSError: The input file cannot be read.
    """
    with filename.open(encoding="utf-8-sig") as source:
        records = json.load(source)
    if not isinstance(records, list) or any(
        not isinstance(record, dict) for record in records
    ):
        raise ValueError(
            f"{filename} must contain a JSON array of applicant objects"
        )
    return records


def prepare_rows(
    records: Iterable[dict[str, Any]],
) -> tuple[list[tuple[object, ...]], int]:
    """Normalize records and remove repeated source URLs.

    Args:
        records: Iterable of applicant dictionaries to validate.

    Returns:
        A pair of ordered database rows and the duplicate-URL count. The
        first record for each URL is retained; input records are unchanged.

    Raises:
        ValueError: A record is invalid; the error names its 1-based position.
    """
    rows: list[tuple[object, ...]] = []
    seen_urls: set[object] = set()
    duplicate_count = 0
    url_index = COLUMNS.index("url")

    for position, record in enumerate(records, start=1):
        try:
            row = normalize_record(record)
        except ValueError as error:
            raise ValueError(f"Record {position}: {error}") from error
        url = row[url_index]
        if url in seen_urls:
            duplicate_count += 1
            continue
        seen_urls.add(url)
        rows.append(row)
    return rows, duplicate_count


def connection_arguments() -> dict[str, object]:
    """Build non-secret connection settings from the environment.

    Returns:
        host, port, dbname, and user settings. DB_* takes precedence over
        PG*; defaults target local gradcafe with the gradcafe_app role.

    Raises:
        ValueError: The configured port is not an integer.
    """
    return {
        "host": os.getenv("DB_HOST", os.getenv("PGHOST", "localhost")),
        "port": int(os.getenv("DB_PORT", os.getenv("PGPORT", "5432"))),
        "dbname": os.getenv("DB_NAME", os.getenv("PGDATABASE", "gradcafe")),
        "user": os.getenv("DB_USER", os.getenv("PGUSER", "gradcafe_app")),
    }


def connect_database(create_if_missing: bool = False) -> psycopg.Connection:
    """Connect directly unless an authorized loader requests provisioning.

    DATABASE_URL takes precedence and connects directly without provisioning.
    Otherwise, environment settings are used and a missing password is
    requested privately only when standard input is interactive.

    Args:
        create_if_missing: Whether an administrator loader may create a
            missing database through the postgres maintenance database.

    Returns:
        An open connection. The caller must commit/rollback and close it.

    Raises:
        RuntimeError: Noninteractive execution has no configured password.
        ValueError: The configured port is invalid.
        psycopg.Error: Authentication, connection, or provisioning fails.
    """
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        return psycopg.connect(database_url)

    arguments = connection_arguments()
    password = os.getenv("DB_PASSWORD", os.getenv("PGPASSWORD"))
    if password is None:
        if not sys.stdin.isatty():
            raise RuntimeError(
                "Set DB_PASSWORD or PGPASSWORD for a noninteractive run"
            )
        password = getpass.getpass(
            f"Password for PostgreSQL user {arguments['user']}: "
        )

    if create_if_missing:
        database_name = str(arguments["dbname"])
        maintenance_arguments = dict(arguments)
        maintenance_arguments["dbname"] = "postgres"
        with psycopg.connect(
            password=password,
            autocommit=True,
            **maintenance_arguments,
        ) as maintenance_connection:
            with maintenance_connection.cursor() as cursor:
                cursor.execute(
                    "SELECT 1 FROM pg_database WHERE datname = %s LIMIT 1",
                    (database_name,),
                )
                if cursor.fetchone() is None:
                    # Database names are identifiers, not bound values. Quote
                    # with Identifier; never insert the raw environment text.
                    statement = sql.SQL("CREATE DATABASE {}").format(
                        sql.Identifier(database_name)
                    )
                    cursor.execute(statement)
                    print(f"Created PostgreSQL database: {database_name}")
    return psycopg.connect(password=password, **arguments)


def batches(
    rows: Sequence[tuple[object, ...]], batch_size: int
) -> Iterable[Sequence[tuple[object, ...]]]:
    """Yield bounded batches for efficient inserts.

    Args:
        rows: Ordered normalized tuples ready for parameter binding.
        batch_size: Positive maximum number of rows in each yielded slice.

    Yields:
        Consecutive slices of rows, with a possibly shorter final slice.
    """
    for start in range(0, len(rows), batch_size):
        yield rows[start : start + batch_size]


def verify_schema(cursor: psycopg.Cursor) -> int:
    """Verify the live table structure, primary key, and URL uniqueness.

    Args:
        cursor: Open cursor with access to applicants and schema metadata.

    Returns:
        The number of distinct stored URLs after all checks pass.

    Raises:
        RuntimeError: Columns, identity, primary key, or row uniqueness do
            not match expectations. This checks data uniqueness, not the
            presence of a separate UNIQUE constraint in metadata.
        psycopg.Error: A validation query cannot be executed.
    """
    cursor.execute(
        """
        SELECT column_name, data_type, is_identity
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'applicants'
        ORDER BY ordinal_position
        LIMIT 100
        """
    )
    column_rows = cursor.fetchall()
    actual_schema = {name: data_type for name, data_type, _ in column_rows}
    if actual_schema != EXPECTED_SCHEMA:
        raise RuntimeError(
            "The live applicants table does not match the required schema"
        )

    identity_columns = [
        name for name, _, is_identity in column_rows if is_identity == "YES"
    ]
    if identity_columns != ["p_id"]:
        raise RuntimeError("p_id must be the table's identity column")

    cursor.execute(
        """
        SELECT kcu.column_name
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_name = kcu.constraint_name
         AND tc.table_schema = kcu.table_schema
        WHERE tc.table_schema = 'public'
          AND tc.table_name = 'applicants'
          AND tc.constraint_type = 'PRIMARY KEY'
        ORDER BY kcu.ordinal_position
        LIMIT 100
        """
    )
    if [row[0] for row in cursor.fetchall()] != ["p_id"]:
        raise RuntimeError("p_id must be the applicants primary key")

    cursor.execute(
        """
        SELECT count(*), count(DISTINCT url)
        FROM applicants
        LIMIT 1
        """
    )
    row_count, unique_url_count = cursor.fetchone()
    if row_count != unique_url_count:
        raise RuntimeError("applicants contains duplicate URLs")
    return unique_url_count


def load_rows(
    rows: Sequence[tuple[object, ...]], batch_size: int
) -> tuple[int, int, int]:
    """Create, load, and validate the table in one transaction.

    Args:
        rows: Normalized tuples whose order matches COLUMNS.
        batch_size: Positive maximum number of rows per executemany call.

    Returns:
        Counts before loading, after loading, and of distinct stored URLs.
        Existing URL conflicts are ignored rather than overwritten.

    Raises:
        RuntimeError: Configuration or post-insert schema validation fails.
        psycopg.Error: Provisioning, insertion, or verification fails.
    """
    # The connection context commits only after verification succeeds. Any
    # failure rolls back this table transaction instead of leaving half a load.
    with connect_database(create_if_missing=True) as connection:
        with connection.cursor() as cursor:
            cursor.execute(CREATE_TABLE_SQL)
            cursor.execute("SELECT count(*) FROM applicants LIMIT 1")
            before = cursor.fetchone()[0]
            for batch in batches(rows, batch_size):
                cursor.executemany(INSERT_SQL, batch)
            cursor.execute("SELECT count(*) FROM applicants LIMIT 1")
            after = cursor.fetchone()[0]
            unique_url_count = verify_schema(cursor)
    return before, after, unique_url_count


def parse_args() -> argparse.Namespace:
    """Parse command-line settings that do not contain credentials.

    Returns:
        Parsed file path and batch size. Invalid CLI syntax exits through
        argparse before any database operation is attempted.
    """
    parser = argparse.ArgumentParser(
        description="Load cleaned GradCafe records into PostgreSQL."
    )
    parser.add_argument(
        "--file",
        type=Path,
        default=DEFAULT_INPUT,
        help="cleaned JSON file (default: llm_extend_applicant_data.json)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=1000,
        help="records per database batch (default: 1000)",
    )
    arguments = parser.parse_args()
    if arguments.batch_size < 1:
        parser.error("--batch-size must be at least 1")
    return arguments


def main() -> int:
    """Load the input and print a concise, reproducible summary."""
    arguments = parse_args()
    try:
        records = read_records(arguments.file)
        rows, source_duplicates = prepare_rows(records)
        before, after, unique_url_count = load_rows(
            rows, arguments.batch_size
        )
    except (OSError, ValueError, RuntimeError, psycopg.Error) as error:
        print(f"Load failed: {error}", file=sys.stderr)
        return 1

    print(f"Source records: {len(records):,}")
    print(f"Usable unique records: {len(rows):,}")
    print(f"Duplicate source URLs skipped: {source_duplicates:,}")
    print(f"Rows before load: {before:,}")
    print(f"Rows inserted: {after - before:,}")
    print(f"Rows after load: {after:,}")
    print(f"Unique URLs after load: {unique_url_count:,}")
    print("Schema and primary-key verification: passed")
    return 0


if __name__ == "__main__":  # pragma: no cover - module execution bootstrap
    raise SystemExit(main())
